### ISSUE TITLE
Use @Data

### ISSUE THREAD

**Issue by discospiff** [reediculous456/InventoryManager#35]
There are several annotations here.  Can you consolidate these by simply using `@Data`?

https://github.com/reediculous456/InventoryManager/blob/8964af4bd1f3e2b7dcb089befdc3778955604557/src/main/java/edu/uc/inventorymanager/dto/Item.java#L9

**Comment by reediculous456** [comment]
@discospiff According to many sources including the IntelliJ JPA plugin, using `@Data` on JPA classes can lead to many bad side-effects

https://dzone.com/articles/lombok-and-jpa-what-may-go-wrong
